//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeleClient {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class AppSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppSettings defaultInstance = ((AppSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppSettings())));
        
        public static AppSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>0</string>
  <string>2048</string>
  <string>2048</string>
  <string>2048</string>
  <string>1037</string>
  <string>3245</string>
  <string>2135</string>
  <string>2048</string>
  <string>2048</string>
  <string>2048</string>
  <string>2925</string>
  <string>1176</string>
  <string>2045</string>
  <string>2079</string>
  <string>2040</string>
  <string>2073</string>
  <string>2048</string>
  <string>2048</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection zerob {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["zerob"]));
            }
            set {
                this["zerob"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com5")]
        public string com {
            get {
                return ((string)(this["com"]));
            }
            set {
                this["com"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>0</string>
  <string>hello</string>
  <string>2</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection action {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["action"]));
            }
            set {
                this["action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>0</string>
  <string>2048</string>
  <string>2048</string>
  <string>2048</string>
  <string>1037</string>
  <string>3245</string>
  <string>2135</string>
  <string>2048</string>
  <string>2048</string>
  <string>2048</string>
  <string>2925</string>
  <string>1176</string>
  <string>2045</string>
  <string>2079</string>
  <string>2040</string>
  <string>2073</string>
  <string>2048</string>
  <string>2048</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection zeroPosition {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["zeroPosition"]));
            }
            set {
                this["zeroPosition"] = value;
            }
        }
    }
}
